(LABS)/CarDealership/CarDealership/Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CarDealership.Models
{
    public class Car : IValidatableObject
    {
        public int Id { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Year { get; set; }
        public string ImageUrl { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public decimal? Price { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            List<ValidationResult> errors = new List<ValidationResult>();

            if (Make == null)
            {
                errors.Add(new ValidationResult("Please enter the vehicle Make.", new [] { "Make" }));
            }

            if (Model == null)
            {
                errors.Add(new ValidationResult("Please enter the vehicle Model.", new [] { "Model" }));
            }

            if ((Year == null) || (Year.Length != (4)))
            {
                errors.Add(new ValidationResult("Please enter the four digit vehicle Year.", new [] { "Year" }));
            }

            if (Title == null)
            {
                errors.Add(new ValidationResult("Please enter the vehicle Description.", new [] { "Title" }));
            }

            if ((Price == null) || (Price < 1000M))
            {
                errors.Add(new ValidationResult("Please enter a vehicle Price. Vehicle Price must be at least $1,000.00", new [] { "Price" }));
            }

            return errors;
        }
    }
}

(LABS)/CarDealership/CarDealership/Controllers/CarController.cs
using CarDealership.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using System.Web.WebPages;
using CarDealership.Models;

namespace CarDealership.Controllers
{
    public class CarController : Controller
    {
        ICarRepository _repo = new DBCarRepository();

        // GET: Car
        public ActionResult Index()
        {
            var cars = _repo.GetAllCars();
            return View(cars);
        }

        public ActionResult Details(int id)
        {
            var car = _repo.GetCarById(id);
            return View(car);
        }

        public ActionResult Add()
        {
            return View("Add");
        }

        public ActionResult Confirmation()
        {
            return View("Confimation");
        }        

        public ActionResult Edit(int id)
        {
            Car car = _repo.GetCarById(id);
            return View(car);
        }

        public ActionResult Delete(int id)
        {
            Car car = _repo.GetCarById(id);
            return View(car);
        }

        [HttpPost]
        public ActionResult AddCar(Car car)
        {
            ICarRepository _car = new DBCarRepository();
            ViewBag.Message = "Add a new vehicle by filling out the form below.";

            car.Make = Request.Form["Make"];
            car.Model = Request.Form["Model"];
            car.Year = Request.Form["Year"];
            car.ImageUrl = Request.Form["ImageUrl"];
            car.Title = Request.Form["Title"];
            car.Description = Request.Form["Description"];
            car.Price = Request.Form["Price"].AsDecimal();

            if (ModelState.IsValid)
            {
                _car.AddCar(car);
                return RedirectToAction("Confirmation");
            }
            else
            {
                return View("Add");
            }
        }

        public ActionResult EditCar(Car car)
        {
            if (ModelState.IsValid)
            {
                _repo.EditCar(car);
                return RedirectToAction("Index");
            }
            else
            {
                return View("Edit");
            }
        }

        public ActionResult DeleteCar(int id)
        {
            _repo.DeleteCar(id);
                return View("Deleted");
        }
    }
}

(LABS)/CarDealership/CarDealership/Views/Car/Add.cshtml
@model CarDealership.Models.Car


<h2>Add New Vehicle</h2>

@using (Html.BeginForm("AddCar", "Car", FormMethod.Post))
{
    <div>
        @Html.ValidationSummary()
    </div>
    <div>
        <div class="form-group">
            <label>Make</label><br/>
            @Html.TextBoxFor(m => m.Make)<br/>
            @Html.ValidationMessageFor(m => m.Make)<br/>
        </div>
        <div class="form-group">
            <label>Model</label><br/>
            @Html.TextBoxFor(m => m.Model)<br/>
            @Html.ValidationMessageFor(m => m.Model)<br/>
        </div>
        <div class="form-group">
            <label>Year</label><br/>
            @Html.TextBoxFor(m => m.Year)<br/>
            @Html.ValidationMessageFor(m => m.Year)<br/>
        </div>
        <div class="form-group">
            <label>Title</label><br/>
            @Html.TextBoxFor(m => m.Title)<br/>
            @Html.ValidationMessageFor(m => m.Title)<br/>
        </div>
        <div class="form-group">
            <label>Description (optional)</label><br/>
            @Html.TextAreaFor(m => m.Description)<br/>
            
        </div>
        <div class="form-group">
            <label>Price</label><br/>
            @Html.TextBoxFor(m => m.Price)<br/>
            @Html.ValidationMessageFor(m => m.Price)<br/>
        </div>
        <div class="form-group">
            <label>Image URL (optional)</label><br/>
            @Html.TextBoxFor(m => m.ImageUrl)<br/>
        </div>
        <button>Submit</button>
    </div>
}

(LABS)/CarDealership/CarDealership/Views/Car/Confimation.cshtml
@{
    ViewBag.Title = "Confirmation";
}

<h2>Vehicle submitted successfully.</h2>
@Html.ActionLink("Add another vehicle", "Add", "Car")<br/>
@Html.ActionLink("Back to vehicles", "Index", "Car")

(LABS)/CarDealership/CarDealership/Views/Car/Delete.cshtml
@model CarDealership.Models.Car
@{
    ViewBag.Title = "Delete";
}

<h2>Are you sure you want to delete this vehicle?</h2>
@using (Html.BeginForm("DeleteCar", "Car", FormMethod.Post))
{ 
    @Html.HiddenFor(m => m.Id)
<div>
    <div class="form-group">
        <label>Make</label><br />
        @Html.DisplayFor(m => m.Make)<br />
    </div>
    <div class="form-group">
        <label>Model</label><br />
        @Html.DisplayFor(m => m.Model)<br />
    </div>
    <div class="form-group">
        <label>Year</label><br />
        @Html.DisplayFor(m => m.Year)<br />
    </div>
    <div class="form-group">
        <label>Title</label><br />
        @Html.DisplayFor(m => m.Title)<br />
    </div>
    <div class="form-group">
        <label>Description (optional)</label><br />
        @Html.DisplayFor(m => m.Description)<br />

    </div>
    <div class="form-group">
        <label>Price</label><br />
        @Html.DisplayFor(m => m.Price)<br />
    </div>
    <div class="form-group">
        <label>Image URL (optional)</label><br />
        @Html.DisplayFor(m => m.ImageUrl)<br />
    </div>
    <button>Delete</button>
</div>
}

(LABS)/CarDealership/CarDealership/Views/Car/Deleted.cshtml
@{
    ViewBag.Title = "Deleted";
}

<h2>Vehicle deleted.</h2>
@Html.ActionLink("Back to vehicles", "Index", "Car")

(LABS)/CarDealership/CarDealership/Views/Car/Details.cshtml
@model CarDealership.Models.Car
@{
    ViewBag.Title = "Details";
}
<h2>@Model.Title</h2>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <img src="@Model.ImageUrl" alt="A car" class="car-image"/>
        </div>
@using (Html.BeginForm("Edit", "Car", new {id=Model.Id}, FormMethod.Post))
{
        <div>         
            <button>Edit</button>
        </div>
}
        <div>
            @Html.ActionLink("Delete this vehicle", "Delete", "Car", new { id = Model.Id }, null)
        </div>

        <div class="col-md-8">
            <div>
                @Model.Description
            </div>
            <h1>ONLY @string.Format("{0:C}", Model.Price)!!</h1><br />
            <h1>@string.Format(Model.Description)</h1>
        </div>
    </div>
</div>

(LABS)/CarDealership/CarDealership/Views/Car/Edit.cshtml
@model CarDealership.Models.Car


<h2>Edit Vehicle</h2>

@using (Html.BeginForm("EditCar", "Car", FormMethod.Post))
{
    <div>
        @Html.ValidationSummary(true)
        @Html.HiddenFor(m => m.Id)
    </div>
    <div>
        <div class="form-group">
            <label>Make</label><br />
            @Html.EditorFor(m => m.Make)<br />
            @Html.ValidationMessageFor(m => m.Make)<br />
        </div>
        <div class="form-group">
            <label>Model</label><br />
            @Html.EditorFor(m => m.Model)<br />
            @Html.ValidationMessageFor(m => m.Model)<br />
        </div>
        <div class="form-group">
            <label>Year</label><br />
            @Html.EditorFor(m => m.Year)<br />
            @Html.ValidationMessageFor(m => m.Year)<br />
        </div>
        <div class="form-group">
            <label>Title</label><br />
            @Html.EditorFor(m => m.Title)<br />
            @Html.ValidationMessageFor(m => m.Title)<br />
        </div>
        <div class="form-group">
            <label>Description (optional)</label><br />
            @Html.EditorFor(m => m.Description)<br />

        </div>
        <div class="form-group">
            <label>Price</label><br />
            @Html.EditorFor(m => m.Price)<br />
            @Html.ValidationMessageFor(m => m.Price)<br />
        </div>
        <div class="form-group">
            <label>Image URL (optional)</label><br />
            @Html.EditorFor(m => m.ImageUrl)<br />
        </div>
        <button>Update</button>
    </div>
}

(LABS)/CarDealership/CarDealership/Views/Car/Index.cshtml
@model IEnumerable<CarDealership.Models.Car>

@{
    ViewBag.Title = "Index";
}

<h2>Check out these fine, high-quality cars for sale! CLICK IMAGE FOR DETAILS!</h2>

<div class="container">
    @Html.ActionLink("Add New Vehicle", "Add", "Car")
    @for (int i = 0; i < Model.Count(); i = i+3 )
        {
           var ca = Model.ElementAt(i);
            <div class="row">
                <div class="col-md-4">
                    <a href="@Url.Action("Details", new {id = ca.Id})">
                        <img src="@ca.ImageUrl" alt="This is a car for sale" class="car-image"/>
                    </a>
                </div>
                @if ((i + 1) < Model.Count())
                {
                    ca = Model.ElementAt(i + 1);
                    <div class="col-md-4">
                        <a href="@Url.Action("Details", new {id = ca.Id})">
                            <img src="@ca.ImageUrl" alt="This is a car for sale" class="car-image"/>
                        </a>
                    </div>
                }
                @if ((i + 2) < Model.Count())
                {
                    ca = Model.ElementAt(i + 2);
                    <div class="col-md-4">
                        <a href="@Url.Action("Details", new {id = ca.Id})">
                            <img src="@ca.ImageUrl" alt="This is a car for sale" class="car-image"/>
                        </a>
                    </div>
                }
            </div>
            <div>&nbsp;
            </div>
        }    
</div>